#!/usr/bin/env bash

set -e

DOCKER=${DOCKER:-docker}
RUGPI_IMAGE=${RUGPI_IMAGE:-ghcr.io/silitics/rugpi-bakery:latest}

$DOCKER run --rm --privileged \
    -v "$(pwd)":/project \
    -v /dev:/dev \
    --pull always \
    "$RUGPI_IMAGE" \
    "$@"
