#!/bin/sh
##################################################
# Parse firmware file marker
#
# Example file contents:
# ```
# tedge_rugpi_default_pi45_20231203.1557
# ```
##################################################
set -e
ARTIFACT_FILE=/etc/.build_info

if [ ! -f "$ARTIFACT_FILE" ]; then
    exit 0
fi

NAME=$(rev /etc/.build_info | cut -d_ -f2- | rev)
VERSION=$(rev /etc/.build_info | cut -d_ -f1 | rev)

echo "name=\"$NAME\""
echo "version=\"$VERSION\""

# FIXME: Workaround since thin-edge.io does deduplication detection.
# However this is only needed because the firmware/name is cleared on tedge-agent startup.
# Remove once https://github.com/thin-edge/thin-edge.io/issues/2497 is resolved
echo "updated=\"$(date)\""
